
function callError(data,ioArgs){
	console.log(data);
}
